FROM ebbe52e5/bitcoin-base:v1.0 as builder
LABEL maintainer="ETHAN LIU <ebbe52e5@gmail.com>"
LABEL description="Bitcoin Core Docker Image"

ENV DISABLE_WALLET=0
ENV BUILD_JETS=2

ENV SRC_DIR=/usr/local/src/bitcoin
ENV VERSION="1.26.0"
ENV GITHUB_SOURCE_URL="https://github.com/satshub/bitcoin.git"
ENV COIN_TMP="/var/tmp"
ENV COIN_CONF_FILE="${COIN_ROOT_DIR}/config.conf"

RUN apt-get update -y \
    && apt-get install -y \
        automake \
        autotools-dev \
        bsdmainutils \
        build-essential \
        git \
        vim \
        libboost-chrono-dev \
        libboost-filesystem-dev \
        libboost-system-dev \
        libboost-test-dev \
        libboost-thread-dev \
        libevent-dev \
        libminiupnpc-dev \
        libssl-dev \
        libtool \
        libzmq3-dev \
        pkg-config \
        python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR $SRC_DIR

RUN git clone -n $GITHUB_SOURCE_URL $SRC_DIR \
    && cd $SRC_DIR \
    && git checkout ${VERSION:+tags/v}${VERSION:-master}

RUN ./autogen.sh

RUN make -C depends NO_BOOST=1 NO_LIBEVENT=1 NO_QT=1 NO_SQLITE=1 NO_NATPMP=1 NO_UPNP=1 NO_ZMQ=1 NO_USDT=1
ENV BDB_PREFIX="${SRC_DIR}/depends/x86_64-pc-linux-gnu"
RUN  ./configure \
    BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" \
    BDB_CFLAGS="-I${BDB_PREFIX}/include" \
    --without-gui \
    --disable-tests \
    --disable-bench 

RUN V=1 make -j${BUILD_JETS}



FROM ebbe52e5/bitcoin-base:v1.0

ENV COIN_CONF_FILE="${COIN_ROOT_DIR}/config.conf"

RUN apt-get update -y \
    && apt-get install -y \
        libboost-chrono-dev \
        libboost-filesystem-dev \
        libboost-system-dev \
        libboost-test-dev \
        libboost-thread-dev \
        libevent-dev \
        libminiupnpc-dev \
        libssl-dev \
        libzmq3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=builder /usr/local/src/bitcoin/src/bitcoind /usr/bin/
COPY --from=builder /usr/local/src/bitcoin/src/bitcoin-cli /usr/bin/
COPY "docker-entrypoint.sh" /entrypoint.sh
COPY "config.conf" "${COIN_CONF_FILE}"
COPY "scripts/" "${COIN_SCRIPTS}/"

RUN chown -R coinuser:coingroup "${COIN_ROOT_DIR}/"

EXPOSE 8332 18332 18443 8333 18333 18444

VOLUME ["${COIN_ROOT_DIR}"]

ENTRYPOINT ["/entrypoint.sh"]

CMD ["bitcoind"]
