FROM ebbe52e5/bitcoin-base:v1.0
LABEL maintainer="ETHAN LIU <ebbe52e5@gmail.com>"
LABEL description="Bitcoin Core Docker Image"

ENV DISABLE_WALLET=0
ENV BUILD_JETS=2

ENV SRC_DIR=/usr/local/src/bitcoin
ENV VERSION="26.0"
ENV GITHUB_SOURCE_URL="https://github.com/bitcoin/bitcoin.git"
ENV COIN_TMP="/var/tmp"
ENV COIN_CONF_FILE="${COIN_ROOT_DIR}/config.conf"

RUN apt-get update -y \
    && apt-get install -y \
        automake \
        autotools-dev \
        bsdmainutils \
        build-essential \
        git \
        vim \
        libboost-chrono-dev \
        libboost-filesystem-dev \
        libboost-system-dev \
        libboost-test-dev \
        libboost-thread-dev \
        libevent-dev \
        libminiupnpc-dev \
        libssl-dev \
        libtool \
        libzmq3-dev \
        pkg-config \
        python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR $SRC_DIR

RUN git clone -n $GITHUB_SOURCE_URL $SRC_DIR \
    && cd $SRC_DIR \
    && git checkout ${VERSION:+tags/v}${VERSION:-master}

RUN ./autogen.sh

RUN  ./configure \
    --with-incompatible-bdb \
    --without-gui \
    --disable-tests \
    --disable-bench 

RUN V=1 make -j${BUILD_JETS}
