FROM ebbe52e5/bitcoin-base:v1.0
LABEL maintainer="ETHAN LIU <ebbe52e5@gmail.com>"
LABEL description="Bitcoin Core Docker Image"

ENV DISABLE_WALLET
ENV BUILD_JETS=2

ENV VERSION="26.0"
ENV GITHUB_SOURCE_URL="https://github.com/satshub/bitcoin.git"
ENV COIN_TMP="/var/tmp"
ENV COIN_CONF_FILE="${COIN_ROOT_DIR}/config.conf"

RUN apt-get update -y \
    && apt-get install -y \
        automake \
        autotools-dev \
        bsdmainutils \
        build-essential \
        git \
        ${DISABLE_WALLET-libdb-dev} \
        ${DISABLE_WALLET-libdb++-dev} \
        libboost-chrono-dev \
        libboost-filesystem-dev \
        libboost-system-dev \
        libboost-test-dev \
        libboost-thread-dev \
        libevent-dev \
        libminiupnpc-dev \
        libssl-dev \
        libtool \
        libzmq3-dev \
        pkg-config \
        python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR $SRC_DIR

RUN git clone -n $GITHUB_SOURCE_URL $SRC_DIR \
    && cd $SRC_DIR \
    && git checkout ${VERSION:+tags/v}${VERSION:-master}

RUN ./autogen.sh

RUN mkdir $BUILDER_DIR

RUN  ./configure \
    ${DISABLE_WALLET---with-incompatible-bdb} \
    ${DISABLE_WALLET+--disable-wallet} \
    --disable-tests \
    --disable-bench \
    --without-gui \
    --prefix=$BUILDER_DIR

RUN V=1 make clean

RUN V=1 make -j${BUILD_JETS}

RUN make install

COPY "docker-entrypoint.sh" /entrypoint.sh
COPY "config.conf" "${COIN_CONF_FILE}"
COPY "scripts/" "${COIN_SCRIPTS}/"

RUN chown -R coinuser:coingroup "${COIN_ROOT_DIR}/"

EXPOSE 8332 18332 18443 8333 18333 18444

VOLUME ["${COIN_ROOT_DIR}"]

ENTRYPOINT ["/entrypoint.sh"]

CMD ["bitcoind"]
